<?php
require_once('libraries/Session.php');
?>
<!DOCTYPE html>
<html lang="en">
  <head>
    <title>Beebee Eco</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
    
    <link href="https://fonts.googleapis.com/css?family=Poppins:200,300,400,500,600,700,800&display=swap" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Lora:400,400i,700,700i&display=swap" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Amatic+SC:400,700&display=swap" rel="stylesheet">

    <link rel="stylesheet" href="css/open-iconic-bootstrap.min.css">
    <link rel="stylesheet" href="css/animate.css">
    
    <link rel="stylesheet" href="css/owl.carousel.min.css">
    <link rel="stylesheet" href="css/owl.theme.default.min.css">
    <link rel="stylesheet" href="css/magnific-popup.css">

    <link rel="stylesheet" href="css/aos.css">

    <link rel="stylesheet" href="css/ionicons.min.css">

    <link rel="stylesheet" href="css/bootstrap-datepicker.css">
    <link rel="stylesheet" href="css/jquery.timepicker.css">

    
    <link rel="stylesheet" href="css/flaticon.css">
    <link rel="stylesheet" href="css/icomoon.css">
    <link rel="stylesheet" href="css/style.css">
  </head>
  <body class="goto-here">
	<main>
   <header>
 <nav class="navbar navbar-expand-lg navbar-dark ftco_navbar bg-dark ftco-navbar-light" id="ftco-navbar">
 
    <!-- <nav class="navbar navbar-inverse bg-inverse fixed-top bg-faded"> -->
	<!-- <div class="row">
		<div class="col">
			<button type="button" class="btn btn-primary" data-toggle="modal" data-target="#cart">Cart (<span class="total-count"></span>)</button><button class="clear-cart btn btn-danger">Clear Cart</button></div>
	</div>
</nav> --> 

	    <div class="container">
	      <a class="navbar-brand" href="index.html">Beebee Eco</a>
	      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#ftco-nav" aria-controls="ftco-nav" aria-expanded="false" aria-label="Toggle navigation">
	        <span class="oi oi-menu"></span> Menu
	      </button>

	      <div class="collapse navbar-collapse" id="ftco-nav">
	        <ul class="navbar-nav ml-auto">
	          <li class="nav-item active"><a href="index.php?controller=Accueil&task=showIndex" class="nav-link">Home</a></li>
	          <li class="nav-item dropdown">
              <a class="nav-link dropdown-toggle" href="#" id="dropdown04" >Shop</a>
              <div class="dropdown-menu" aria-labelledby="dropdown04">
              	<a class="dropdown-item" href="index.php?controller=PanierTest&task=showList">Nos produits</a>
              	<!-- <a class="dropdown-item" href="wishlist.html">Cosmétique</a>
                <a class="dropdown-item" href="product-single.html">Autres</a> -->
                <a class="dropdown-item" href="index.php?controller=PanierTest&task=showCart">Cart</a>
                <!-- <a class="dropdown-item" href="index.php?controller=Shop&task=showShop">test panier</a> -->
                
                <!-- <a class="dropdown-item" href="checkout.html">Checkout</a> -->
              </div>
            </li>
	          <!-- <li class="nav-item"><a href="about.html" class="nav-link">A propos</a></li>
	          <li class="nav-item"><a href="blog.html" class="nav-link">Blog</a></li> -->
              <li class="nav-item"><a href="index.php?controller=Users&task=showContact" class="nav-link">Contact</a></li>
              <li class="nav-item dropdown">
              <a class="nav-link dropdown-toggle" href="#" id="dropdown04">Mon compte</a>
              <div class="dropdown-menu" aria-labelledby="dropdown04">
                <?php if (!Session::isConnected()) : ?>
               
                <a class="dropdown-item" href="index.php?controller=Users&task=formLogin">Connexion</a>
                <a class="dropdown-item" href="index.php?controller=Users&task=showRegister">Inscription</a>
                <?php else : ?>
                <a class="dropdown-item" href="index.php?controller=Users&task=logout">Deconnexion</a>
                
              	<!-- <a class="dropdown-item" href="wishlist.html">Checkout</a> -->
                <?php if ($_SESSION['user']['admin'] == 1) : ?>
                <a class="dropdown-item" href="index.php?controller=Admin&task=showAdm">Administration</a>
                <?php endif ?>
                <?php endif ?>
                <!-- <a class="dropdown-item" href="checkout.html">Checkout</a> -->
              </div>
            </li>
            
	          <li class="nav-item cta cta-colored"><a href="index.php?controller=PanierTest&task=showCart" class="nav-link"><span class="icon-shopping_cart"></span>[0]</a></li>

	        </ul>
	      </div>
	    </div>
    </nav>
    </header>
    <!-- END nav -->
  <?php if (Session::hasFlashes('error')) : ?>
    <div class="errors">
    <?php foreach (Session::getFlashes('error') as $message) : ?>
    <p><?= $message ?></p>
    <?php endforeach ?>
    </div>
    <?php endif ?>
    <?php if (Session::hasFlashes('success')) : ?>
    <div class="success">
    <?php foreach (Session::getFlashes('success') as $message) : ?>
    <p><?= $message ?></p>
    <?php endforeach ?>
    </div>
  <?php endif ?>

   