<?php
if (isset($_SESSION["cart_item"])) {
	$total_quantity = 0;
	$total_price = 0;
}
?>
<h3>Panneau Admin</h3>
<section class="ftco-section">
	<div class="container">
		<div class="row justify-content-center">
			<div class="col-md-10 mb-5 text-center">
				<ul class="product-category">
					<li><a href="#" class="active">All</a></li>
					<li><a href="#">Vegetables</a></li>
					<li><a href="#">Fruits</a></li>
					<li><a href="#">Juice</a></li>
					<li><a href="#">Dried</a></li>
				</ul>
			</div>
		</div>
		<div class="row">

			<div class="col-md-6 col-lg-3 ftco-animate">
				<h3>Editer la page des produits</h3>
				<button><a href="index.php?controller=Admin&task=showProducts">Editer</button>
			
					</div>
					<h3>Insérer une image pour les produits</h3>
					<button><a href="index.php?controller=Admin&task=showForm">Insérer une image</a></button>
					</main>