<?php

?>

<!-- <section class="ftco-section"> -->
<div class="container">
	<h2 class="text_bio"><span>Panneau Admin</span></h2>
	<div class="row justify-content-center">
		
		<h3>Editer la page des produits</h3>
		<button><a href="index.php?controller=Admin&task=showProducts">Editer</button>
	</div>

	<div class="row justify-content-center">
		<h3>Insérer une image pour les produits</h3>
		<button><a href="index.php?controller=Admin&task=showForm">Insérer une image</a></button>
	</div>
	</main>