<?php
if(isset($_SESSION["cart_item"])){
    $total_quantity = 0;
	$total_price = 0;
}
?>	
<section class="ftco-section">
    	<div class="container">
    		<div class="row justify-content-center">
    			<div class="col-md-10 mb-5 text-center">
    				<ul class="product-category">
    					<li><a href="#" class="active">All</a></li>
    					<li><a href="#">Vegetables</a></li>
    					<li><a href="#">Fruits</a></li>
    					<li><a href="#">Juice</a></li>
    					<li><a href="#">Dried</a></li>
    				</ul>
    			</div>
    		</div>
    		<div class="row">
			<?php foreach ($products as $product) :?>
			<div class="col-md-6 col-lg-3 ftco-animate">
			
    				<div class="product">
    					<a href="#" class="img-prod"><img class="img-fluid" src="images/products/<?= $product['img_name']?>" alt="image produit">
    					<div class="overlay"></div>
    					</a>
    					<div class="text py-3 pb-4 px-3 text-center m-auto">
							<h3><a href="#"><?=$product['title']?></a></h3>
							<input type="number" name="qtProductSav">
							<p class="price"><span><?=$product['price'] . "€" ?></span></p>
    						<div class="d-flex">
    							<div class="pricing">
								</div>
								<a href="index.php?controller=Admin&task=editProduct&id=<?= $product['id'] ?>" ><i class="far fa-edit"></i>Editer</a>
	    					</div>
    					</div>
    				</div>
				</div>
				<?php endforeach ?>

				</div> -->
			<form action="index.php?controller=Shop&task=addProduct" method="post">
			<button type="submit" name="commande">Commander</button>
			</form>	
    			
    		<div class="row mt-5">
          <div class="col text-center">
            <div class="block-27">
              <ul>
                <li><a href="#">&lt;</a></li>
                <li class="active"><span>1</span></li>
                <li><a href="#">2</a></li>
                <li><a href="#">3</a></li>
                <li><a href="#">4</a></li>
                <li><a href="#">5</a></li>
                <li><a href="#">&gt;</a></li>
              </ul>
            </div>
          </div>
        </div>
    	</div>
    </section>
	</main>
  
   