<section class="ftco-section">
    	<div class="container">
    		<div class="row">
    			<div class="col-md-6 col-lg-3 ftco-animate">
    				<div class="product">
    					<a href="#" class="img-prod"><img class="img-fluid" src="https://via.placeholder.com/253x220" alt="Colorlib Template">
    						<!-- <span class="status">30%</span> -->
    					</a>
    					<h3><a href="#">Produit vaisselle</a></h3>
		    				<p class="price"><span class="">€5.00</span></p>
							<input type="number"/>
		    		</div>
				</div>
			</div>
		</div>			
</section>
  
   