	<section id="home-section" class="hero">
		  <div class="home-slider owl-carousel">
		  <div class="slider-item" style="background-image: url(images/bg_1.jpg);">
		  </div>
	      </div>
    </section>
	<section class="ftco-section">
    	<div class="container">
    		<div class="row justify-content-center">
    		</div>
    		<div class="row">
			<?php foreach ($products as $product) :?>
			<div class="col-md-6 col-lg-3 ftco-animate">
    				<div class="product">
						<a href="#" class="img-prod"><img  src="https://via.placeholder.com/253x300.png/09f/fff" alt="Colorlib Template">
						<!-- <a href="#" class="img-prod"><img class="img-fluid" src="images/products/<?= $product['img_name']?>" alt="Colorlib Template"> -->
    						<div class="overlay"></div>
    					</a>
    					<div class="text py-3 pb-4 px-3 text-center m-auto">
							<input type="hidden" value=<?=$product['id']?> name="product-id"/>
							<h3><a href="#"><?=$product['title']?></a></h3>
							<!-- <input type="number" name="qty" class="qty-product" > -->
							<p class="price"><span><?=$product['price'] . "€" ?></span></p>
							<!-- <a href="index.php?controller=Panier&task=addToCart&id=<?=$product['id'] ?>">Ajouter au panier</a> -->
    						<div class="d-flex">
    							<div class="pricing">
		    					</div>
	    					</div>
    					</div>
    				</div>
				</div>
			<?php endforeach ?>

				</div>
			<!-- <form action="index.php?controller=Panier&task=showPanier" method="post" class="addForm">
			<button type="submit" name="commande">Commander </button>
			</form>	 -->
    </section>
	</main>
	<!-- <script>
$(document).ready(function(){
    // add to cart button listener
    $('.addForm').on('submit', function(){
 
        // info is in the table / single product layout
        var id = $(this).find('.product-id').text();
        var quantity = $(this).find('.qty-product').val();
 
        // redirect to add_to_cart.php, with parameter values to process the request
        window.location.href = "addToCart.php?id=" + id + "&quantity=" + quantity;
        return false;
    });
});
</script> -->
  
   