	<section id="home-section" class="hero">
		<div class="home-slider owl-carousel">
			<div class="slider-item" style="background-image: url(images/bg_1.jpg);">
			</div>

		</div>


	</section>

	<section class="ftco-section">
		<div class="container">
			<div class="row no-gutters ftco-services">
				<div class="col-md-3 text-center d-flex align-self-stretch ftco-animate">
					<div class="media block-6 services mb-md-0 mb-4">
						<div class="icon bg-color-1 active d-flex justify-content-center align-items-center mb-2">
							<span class="flaticon-shipped"></span>
						</div>
						<div class="media-body">
							<h3 class="heading">Livraison *</h3>
							<span>*sur Saint-Cyr uniquement</span>
						</div>
					</div>
				</div>
				<div class="col-md-3 text-center d-flex align-self-stretch ftco-animate">
					<div class="media block-6 services mb-md-0 mb-4">
					<a href="index.php?controller=PanierTest&task=showList"><div class="icon bg-color-2 d-flex justify-content-center align-items-center mb-2">
							<span class="flaticon-diet"></span>
						</div></a>
						<div class="media-body">
							<h3 class="heading">Produits naturels</h3>
						</div>
					</div>
				</div>
				<div class="col-md-3 text-center d-flex align-self-stretch ftco-animate">
					<div class="media block-6 services mb-md-0 mb-4">
						<div class="icon bg-color-3 d-flex justify-content-center align-items-center mb-2">
							<span class="flaticon-award"></span>
						</div>
						<div class="media-body">
							<h3 class="heading">Qualité supérieure</h3>
						</div>
					</div>
				</div>
				<div class="col-md-3 text-center d-flex align-self-stretch ftco-animate">
					<div class="media block-6 services mb-md-0 mb-4">
					<a href="index.php?controller=Users&task=showContact"><div class="icon bg-color-4 d-flex justify-content-center align-items-center mb-2">
							<span class="flaticon-customer-service"></span>
						</div></a>
						<div class="media-body">
							<h3 class="heading">Renseignements</h3>
							<span></span>
						</div>
					</div>
				</div>
			</div>
		</div>
	</section>


	<section class="ftco-section">
		<div class="container">
			<div class="row justify-content-center mb-3 pb-3">
				<div class="col-md-12 heading-section text-center ftco-animate">
					<h2 class="text_bio"><span>Bienvenue sur le site Bee Bee</span></h2>
				</div>
			</div>
		</div>
		<div class="container">
			<div class="row">
				
					<article class="container olive">
				
					<img class="img_olive" src="images/olivebio.jpg" alt="olivier">
					
					<article class="art_zero">
					<h4 >Zéro déchet - Ecologique - Recyclage</h4>	
							<!-- <div class="col-md-6 heading-section ftco-animate deal-of-the-day ftco-animate"> -->
								<p>Vente de produits naturels d’entretien pour votre maison</p>
								<p>Afin de minimiser notre impact environnemental, je vous propose de réutiliser vos
								contenants plastiques et verres pour réduire les déchets et d’utiliser des produits
								naturels au quotidien !</p>
								<p>L'ensemble des produits vendus sont faits  à partir d'ingrédients naturels sans produits chimiques à base d'huile d'olive
								vous pouvez acheter les produits tout prêts ou les réaliser vous-même.
								</p>
					</article>
					</article>
					
			</div>
		</div>
</section>
		