
<?php
if(isset($_SESSION["cart_item"])){
    $total_quantity = 0;
	$total_price = 0;
}
?>
<h3>Panneau Admin</h3>
<section class="ftco-section">
    	<div class="container">
    		<div class="row justify-content-center">
    			<div class="col-md-10 mb-5 text-center">
    				<ul class="product-category">
    					<li><a href="#" class="active">All</a></li>
    					<li><a href="#">Vegetables</a></li>
    					<li><a href="#">Fruits</a></li>
    					<li><a href="#">Juice</a></li>
    					<li><a href="#">Dried</a></li>
    				</ul>
    			</div>
    		</div>
    		<div class="row">
			<?php foreach ($products as $product) :?>
			<div class="col-md-6 col-lg-3 ftco-animate">
			
    				<div class="product">
    					<a href="#" class="img-prod"><img class="img-fluid" src="https://via.placeholder.com/253x220" alt="Colorlib Template">
    						<div class="overlay"></div>
    					</a>
    					<div class="text py-3 pb-4 px-3 text-center m-auto">
							<h3><a href="#">Editer</a></h3>
    						<div class="d-flex">
    							<div class="pricing">
								
		    					</div>
	    					</div>
    					</div>
    				</div>
				</div>
				<?php endforeach ?>
            </main>


