<?php

if (!isset($_SESSION['panier'])) {
	$panier = "";
	$_SESSION['panier'] = [];
} else {
	$panier = $_SESSION['panier'];
	// $nb= count($panier);
	// echo $nb;
}
$total=0;
?>
<section id="home-section" class="hero">
	<div class="home-slider owl-carousel">
		<div class="slider-item" style="background-image: url(images/bg_1.jpg);">
		</div>
	</div>
</section>
<section class="ftco-section">
	<div class="container">
		<div class="row justify-content-center">
		
		<div class="row">
			<?php
			$i = 0;
			$i < count($products);
			$i++;
			foreach ($products as $product[$i]) :
			?>
				<div class="col-md-6 col-lg-3 ftco-animate">
					<div class="product">
						<a href="#" class="img-prod"><img src="https://via.placeholder.com/253x300.png/09f/fff" alt="Colorlib Template">
							<!-- <a href="#" class="img-prod"><img class="img-fluid" src="images/products/<?= $product['img_name'] ?>" alt="Colorlib Template"> -->
							<!-- <div class="overlay"></div> -->
						</a>
						<div class="text py-3 pb-4 px-3 text-center m-auto">
							<form action="index.php?controller=PanierTest&task=indexPanier" method="POST" class="formpanier" id="formproduct">
							
									<input type="hidden" name="id" value="<?= ucfirst(strtolower($product[$i]->id)) ?>" class="formpanier">
									<h3><a href="#"><?= $product[$i]->title ?></a></h3>
									<p class="price"><span><?= $product[$i]->price . "€" ?></span></p>
									<input type="number" name="quantity"  placeholder="quantité" min="0" class="formpanier">

									<button type="submit" id="add"><strong>+</strong></button>

							</form>
							<div class="d-flex">
								<div class="pricing">
								</div>
							</div>
						</div>
					</div>
				</div>
				<script>

				</script>
			<?php endforeach ?>

		</div>
		</div>
		<!-- <form action="index.php?controller=Panier&task=showPanier" method="post" class="addForm">
			<button type="submit" name="commande">Commander </button>
			</form>	 -->
		
	<h2 class="text_bio"><span>Votre panier</span></h2>
	<table class="commande">
		<thead>
			<tr>
				<th>Produit</th>
				<th>Quantité</th>
				<th>Prix</th>
				<th>Total</th>
				<th>Supprimer</th>

			</tr>
		</thead>

		<tbody>
			
			<?php foreach ($panier as $element) : ?>
				<tr>
					<td>
						<?= $element['product']->title ?>
					</td>
					<td>
						<form action="index.php?controller=PanierTest&task=updateItem" method="post" class="der">
							<input type="hidden" name="id" value="<?= $element['product']->id ?>">
							<input type="number" name="quantity"  placeholder="quantity" min=1 required="required" value="<?= $element['quantity'] ?>" onchange="this.form.submit()">
						</form>
					</td>
					<td><?= $element['product']->price ?>€</td>
					<td><?= $element['quantity'] * $element['product']->price ?> €</td>
					<td>
						<a href="index.php?controller=PanierTest&task=deleteItem&id=<?= $element['product']->id ?>" class="mod">supprimer</a>
					</td>
				</tr>
				<?php $total+= $element['quantity'] * $element['product']->price; ?>
			<?php endforeach ?>
			<tr  >
			<td  colspan="1" class="total"> Total commande : <strong><?=$total ?> € </strong></td>
			<td colspan="4" class="lastTd"><button class="btnCom"><a href="index.php?controller=PanierTest&task=showCommande" class="btn btn-primary py-3 px-5">commander</a></button></td>
			</tr>
		</tbody>

	
	</table>


	</div>
	</div>
	</section>
<!-- <button><a href="index.php?controller=Shop&task=showList" class="mod">continuez la commande</a></button> -->
<script>
	// $(document).ready(function(e){

	// });
	// $("#add").on("click",function(){

	// $("#add").on("click",function(e){
	// 	e.preventDefault(e);
	// window.location.replace("index.php?controller=PanierTest&task=showCart");
	// });


	// $(document).ready(function() {
	//     $(document).on('submit', 'formproduct', function() {
	//       // do your things
	//       return false;
	//      });
	// });
</script>

</main>