<?php
if(isset($_SESSION["cart_item"])){
    $total_quantity = 0;
	$total_price = 0;
}
?>	
<section class="ftco-section">
    	<div class="container">
    		<div class="row justify-content-center">
    			<div class="col-md-10 mb-5 text-center">
    				<ul class="product-category">
    					<li><a href="#" class="active">All</a></li>
    					<li><a href="#">Vegetables</a></li>
    					<li><a href="#">Fruits</a></li>
    					<li><a href="#">Juice</a></li>
    					<li><a href="#">Dried</a></li>
    				</ul>
    			</div>
    		</div>
    		<div class="row">
			<?php foreach ($products as $product) :?>
			<div class="col-md-6 col-lg-3 ftco-animate">
			
    				<div class="product">
    					<a href="#" class="img-prod"><img class="img-fluid" src="https://via.placeholder.com/253x220" alt="Colorlib Template">
    						<div class="overlay"></div>
    					</a>
    					<div class="text py-3 pb-4 px-3 text-center m-auto">
							<h3><a href="#"><?=$product['name']?></a></h3>
							<input type="number" name="qtProductSav">
							<p class="price"><span><?=$product['price']?></span></p>
    						<div class="d-flex">
    							<div class="pricing">
								
		    					</div>
	    					</div>
    					</div>
    				</div>
				</div>
				<?php endforeach ?>
				<!-- <div class="col-md-6 col-lg-3 ftco-animate">
    				<div class="product">
    					<a href="#" class="img-prod"><img class="img-fluid" src="https://via.placeholder.com/253x220" alt="Colorlib Template">
    						<div class="overlay"></div>
    					</a>
    					<div class="text py-3 pb-4 px-3 text-center m-auto">
							<h3><a href="#">Vaisselle</a></h3>
							<input type="number" name="qtProductVaisselle">
							<p class="price"><span>$120.00</span></p>
    						<div class="d-flex">
    							<div class="pricing">
								
		    					</div>
	    					</div>
    					</div>
    				</div>
				</div>
				<div class="col-md-6 col-lg-3 ftco-animate">
    				<div class="product">
    					<a href="#" class="img-prod"><img class="img-fluid" src="https://via.placeholder.com/253x220" alt="Colorlib Template">
    						<div class="overlay"></div>
    					</a>
    					<div class="text py-3 pb-4 px-3 text-center m-auto">
							<h3><a href="#">Savon</a></h3>
							<input type="number" name="qtProduct">
							<p class="price"><span>$120.00</span></p>
    						<div class="d-flex">
    							<div class="pricing">
								
		    					</div>
	    					</div>
    					</div>
    				</div>
				</div>
				<div class="col-md-6 col-lg-3 ftco-animate">
    				<div class="product">
    					<a href="#" class="img-prod"><img class="img-fluid" src="https://via.placeholder.com/253x220" alt="Colorlib Template">
    						<div class="overlay"></div>
    					</a>
    					<div class="text py-3 pb-4 px-3 text-center m-auto">
							<h3><a href="#">Savon</a></h3>
							<input type="number" name="qtProduct">
							<p class="price"><span>$120.00</span></p>
    						<div class="d-flex">
    							<div class="pricing">
								
		    					</div>
	    					</div>
    					</div>
    				</div>
				</div>
				<div class="col-md-6 col-lg-3 ftco-animate">
    				<div class="product">
    					<a href="#" class="img-prod"><img class="img-fluid" src="https://via.placeholder.com/253x220" alt="Colorlib Template">
    						<div class="overlay"></div>
    					</a>
    					<div class="text py-3 pb-4 px-3 text-center m-auto">
							<h3><a href="#">Savon</a></h3>
							<input type="number" name="qtProduct">
							<p class="price"><span>$120.00</span></p>
    						<div class="d-flex">
    							<div class="pricing">
								
		    					</div>
	    					</div>
    					</div>
    				</div>
				</div>
				<div class="col-md-6 col-lg-3 ftco-animate">
    				<div class="product">
    					<a href="#" class="img-prod"><img class="img-fluid" src="https://via.placeholder.com/253x220" alt="Colorlib Template">
    						<div class="overlay"></div>
    					</a>
    					<div class="text py-3 pb-4 px-3 text-center m-auto">
							<h3><a href="#">PQ</a></h3>
							<input type="number" name="qtProductPq">
							<p class="price"><span>$120.00</span></p>
    						<div class="d-flex">
    							<div class="pricing">
								
		    					</div>
	    					</div>
    					</div>
    				</div>
				</div>
				<div class="col-md-6 col-lg-3 ftco-animate">
    				<div class="product">
    					<a href="#" class="img-prod"><img class="img-fluid" src="https://via.placeholder.com/253x220" alt="Colorlib Template">
    						<div class="overlay"></div>
    					</a>
    					<div class="text py-3 pb-4 px-3 text-center m-auto">
							<h3><a href="#">Savon</a></h3>
							<input type="number" name="qtProduct">
							<p class="price"><span>$120.00</span></p>
    						<div class="d-flex">
    							<div class="pricing">
								
		    					</div>
	    					</div>
    					</div>
    				</div>
				</div>
				<div class="col-md-6 col-lg-3 ftco-animate">
    				<div class="product">
    					<a href="#" class="img-prod"><img class="img-fluid" src="https://via.placeholder.com/253x220" alt="Colorlib Template">
    						<div class="overlay"></div>
    					</a>
    					<div class="text py-3 pb-4 px-3 text-center m-auto">
							<h3><a href="#">Savon</a></h3>
							<input type="number"/>
							<p class="price"><span>$120.00</span></p>
    						<div class="d-flex">
    							<div class="pricing">
								
		    					</div>
	    					</div>
    					</div>
    				</div>
				</div> -->
			<form action="index.php?controller=Shop&task=addProduct" method="post">
			<button type="submit" name="commande">Commander </button>
			</form>	
    			
    		<div class="row mt-5">
          <div class="col text-center">
            <div class="block-27">
              <ul>
                <li><a href="#">&lt;</a></li>
                <li class="active"><span>1</span></li>
                <li><a href="#">2</a></li>
                <li><a href="#">3</a></li>
                <li><a href="#">4</a></li>
                <li><a href="#">5</a></li>
                <li><a href="#">&gt;</a></li>
              </ul>
            </div>
          </div>
        </div>
    	</div>
    </section>
    <section>
	<div class="container">
    <div class="row justify-content-center">
    			<div class="col-md-6 text-center d-flex">
		<article>
			<figure>
				<a href="#">
				<img src="https://via.placeholder.com/150"></a>
                <figcaption>Produit vaisselle</figcaption>
			</figure>
			<input type="number" name="name" required>
		</article>
		<article>
			<figure>
				<a href="#">
				<img src="https://via.placeholder.com/150"></a>
                <figcaption>Produit vaisselle</figcaption>
			</figure>
			<input type="number" name="name" required>
		</article>
		<article>
			<figure>
				<a href="#">
				<img src="https://via.placeholder.com/150"></a>
                <figcaption>Produit vaisselle</figcaption>
			</figure>
			<input type="number" name="name" required>
		</article>
		<article>
			<figure>
				<a href="#">
				<img src="https://via.placeholder.com/150"></a>
                <figcaption>Produit vaisselle</figcaption>
			</figure>
			<input type="number" name="name" required>
		</article>


</div>
</div>
</div>

	</section>
  
   