<div class="container">
 <?php 
//  if (!isset($_SESSION['panier'])) {
//     $_SESSION['panier'] = [];
//     }
//     else{
//     $panier = $_SESSION['panier'];
//     // $nb= count($panier);
//     // echo $nb;
// }
?> 
       
<h2 class="text_bio"><span>Votre panier<span></h2>
<table class="commande">
<thead>
    <tr>
    <th>Produit</th>
    <th>Quantité</th>
    <th>Prix</th>
    <th>Total</th>
    <th>Supprimer</th>
 
    </tr>
</thead>

<tbody>
    <?php foreach ($panier as $element) :?>
    <tr>
        <td>
            <?= $element['product']->title ?>
        </td>
        <td>
            <form action="index.php?controller=PanierTest&task=updateItem" method="post" class="der" >
                <input type="hidden" name="id" value="<?= $element['product']->id ?>">
                <input type="number" name="quantity" id="" placeholder="quantity" min=1 required="required" value="<?= $element['quantity'] ?>" onchange="this.form.submit()">
            </form>    
        </td>
        <td><?= $element['product']->price ?>€</td>
        <td><?= $element['quantity'] * $element['product']->price ?> €</td>
        <td>
            <a href="index.php?controller=PanierTest&task=deleteItem&id=<?= $element['product']->id ?>" class="mod">supprimer</a>
        </td>
    </tr>
    <?php endforeach ?>
</tbody>


</table>
<!-- // SELECT plats.id, plats.photo, plats.nom_plat, plats.prix, orders_plat.quantity, (plats.prix* orders_plat.quantity) as total
FROM plats
JOIN orders_plat ON orders_plat.plat_id=plats.id
WHERE orders_plat.order_id=1 -->
<button><a href="index.php?controller=PanierTest&task=showCommande" class="mod">commander</a></button>
<button><a href="index.php?controller=Shop&task=showList" class="mod">continuez la commande</a></button>
<!-- <script>
document.querySelector('mod').onclick = function(){
    return false;
}
</script> -->
</div>
</main>
