
<?php
$_SESSION['total']=$_POST['total'];

?>
<div class="container">
<h2 class="text_bio"><span>Précisez vos coordonnées pour la livraison</span></h2>
<form action="index.php?controller=PanierTest&task=loadOrders" method="POST" class="order">
<label for="name">Nom</label>
<input type="text" placeholder="nom" required="required" name="nom" class="form-control">
<label for="firstname">Prenom</label>
<input type="text" placeholder="prenom" required="required" name="prenom" class="form-control">
<label for="email">Email</label>
<input type="text" placeholder="email" required="required" name="mail" class="form-control">
<label for="phone">Téléphone</label>
<input type="text" placeholder="numéro de téléphone" required="required" name="phone" class="form-control">
<label for="Adress">Adresse</label>
<input type="text" placeholder="Adresse" required="required" name="address" class="form-control">
<h3>Livraison</h3>
<label for="livraison">Livraison gratuite à domicile (Saint-Cyr sur mer)</label>
<input type="radio"  name="livraison" value="domicile" >
<label for="point">Point livraison mardi ou jeudi</label>
<input type="radio"  name="livraison" value="point_livraison" >

<h3>Paiement</h3>
<label for="paylivraison">à la livraison</label>
<input type="radio" rows="5" name="pay" value="1">
<label for="cb">CB en ligne</label>
<input type="radio" rows="5" name="pay" value="2">

<h3>Total</h3>
<p> Total de la commande : <?= $_POST['total']?></p>

<!-- <label for="phone">Stripe</label>
<input type="checkbox" required="required" rows="5" name="stripe" value="stripe"> -->

<button type="submit" class="btn btn-primary py-3 px-5">Commandez</button>

</form>
</div>