<div class="container">
  <form class="formul" action="index.php?controller=Users&task=login" method="POST" >
        <h2 class="text_bio"><span>Connexion</span></h2>
     
        <label>Email</label>
         <input type="text" name="email" placeholder="email">
         <label>Mot de passe</label>
         <input type="password" name="password" placeholder="password">
        
    <button type="submit">Envoi</button>

    </form>
</div>
  </main>  
