<div class="hero-wrap hero-bread" style="background-image: url('images/bg_1.jpg');">
  <div class="container">
    <div class="row no-gutters slider-text align-items-center justify-content-center">
      <!-- <div class="col-md-9 ftco-animate text-center">
          	<p class="breadcrumbs"><span class="mr-2"><a href="index.html">Home</a></span> <span>Contact us</span></p>
            <h1 class="mb-0 bread">Contact us</h1>
          </div> -->
    </div>
  </div>
</div>


<div class="row justify-content-center">
  <!-- <div class="col-md-12 order-md-last d-flex"> -->
    <form action="index.php?controller=Users&task=sendMailContact" class="bg-white p-5 contact-form" method="post">

      <div class="form-group">
      <input type="text" name="email" class="form-control" placeholder="mail">

      <input type="text" name="nom" class="form-control" placeholder="Nom">


      <input type="text" name="prenom" class="form-control" placeholder="Prenom">


      <input type="text" name="sujet" class="form-control" placeholder="Sujet">
      

      <textarea name="msg" cols="30" rows="7" class="form-control" placeholder="Message"></textarea>
      <input type="submit" value="Envoyer message" class="btn btn-primary py-3 px-5">

    </form>
  </div>
</div>