
<form action="index.php?controller=Users&task=saveUsers" method="POST" class="formul">
<h2 class="text_bio"><span>Connexion</span></h2>
        <label>Nom</label>
        <input type="text" name="nom" placeholder="nom">
        <label>Prenom</label>
        <input type="text" name="prenom" placeholder="prenom">
        <label>Email</label>
         <input type="text" name="email" placeholder="email">
         <label>Mot de passe</label>
         <input type="password" name="password" placeholder="password">
         <label>Confirmation du mot de passe</label>
        <input type="password" name="passwordconfirm" placeholder="password confirmation">
        
    <button type="submit">Envoi</button>
</form>
</main>