<?php 
if($datasUser[0]->pay_choose==1){
    $pay="Paiement à la livraison";
}
else if ($datasUser[0]->pay_choose==2){
    $pay="Paiement en CB sur le site";
}
?>
<div class="container">
<h2 class="text_bio"><span>Merci  <?php echo $_SESSION['user'] ?>  pour votre commande</span></h2>
<h3 class="address">Coordonnées pour la commande</h3>
<address>
   <p>choix livraison : <?= $datasUser[0]->livraison; ?></p>
   <p> Adresse : <?= $datasUser[0]->address; ?></p>
    <p>Téléphone : <?= $datasUser[0]->phone; ?></p>
    <p>Paiement : <?= $pay ?></p>
</address>
<h2 class="text_bio"><span>Votre panier<span></h2>

<?php   $totalElement=0;
    foreach ($panier as $id => $element) {
    $quantity = $element['quantity'];
   $totalElement += $element['quantity'] * $element['product']->price;

   } ?>

<table class="commande">
<thead>
    <tr>
    <th>Produit</th>
    <th>Quantité</th>
    <th>Prix</th>
    <th>Total</th>
 
    </tr>
</thead>

<tbody>

    <?php 
    
    foreach ($panier as $element) : ?>
    
    <tr>
        <td>
        <?= $element['product']->title ?>
        </td>
        <td><?= $element['quantity'] ?></td>
        <td><?= $element['product']->price ?>€</td>
        <td><?= $element['quantity'] * $element['product']->price ?> €</td>
    
    </tr>
    <?php endforeach ?>
    <tr>
    <td colspan="1" class="total">Total commande : <?=$totalElement ?> €</td>
    <td colspan="3" class="lastTd"></td>
    </tr>
  
   
</tbody>

</table>
</div>
</main>

<?php  

  ?> 