<?php var_dump($panier);
var_dump($_SESSION['panier']);
?>
<div class="container">
<h2 class="text_bio"><span>Merci  <?php echo $prenom . " " . $nom ?>  pour votre commande</span></h2>
<h3 class="address">Coordonnées</h3>
<address>
   <p>choix livraison : <?= $livraison ?></p>
   <p> Adresse :<?= $address ?></p>
    <p>Téléphone :<?= $phone ?></p>
</address>
<h2 class="text_bio"><span>Votre panier<span></h2>

<?php   $totalElement=0;
    foreach ($panier as $id => $element) {
    $quantity = $element['quantity'];
   $totalElement += $element['quantity'] * $element['product']->price;

   } ?>

<table class="commande">
<thead>
    <tr>
    <th>Produit</th>
    <th>Quantité</th>
    <th>Prix</th>
    <th>Total</th>
 
    </tr>
</thead>

<tbody>

    <?php 
    
    foreach ($panier as $element) : ?>
    
    <tr>
        <td>
        <?= $element['product']->title ?>
        </td>
        <td><?= $element['quantity'] ?></td>
        <td><?= $element['product']->price ?>€</td>
        <td><?= $element['quantity'] * $element['product']->price ?> €</td>
    </tr>
    <?php endforeach ?>

</tbody>

</table>
</div>
</main>

<?php  

  ?> 