
<h1>Merci  <?php echo $prenom . " " . $nom ?>  pour votre commande</h1>
<h3 class="address">Coordonnées</h3>
<address>
   <p>choix livraison : <?= $livraison ?></p>
   <p> Adresse :<?= $address ?></p>
    <p>Téléphone :<?= $phone ?></p>
</address>
<h2 class="text_bio"><span>Votre panier<span></h2>

<?php   $totalElement=0;
    foreach ($panier as $id => $element) {
  $quantity = $element['quantity'];
  echo $quantity;

   $totalElement += $element['quantity'] * $element['product']->price;

   } ?>
   <p>Total : <?php echo $totalElement?></p>
<table class="commande">
<thead>
    <tr>
    <th>Produit</th>
    <th>Quantité</th>
    <th>Prix</th>
    <th>Total</th>
 
    </tr>
</thead>

<tbody>
    <?php foreach ($panier as $element) : ?>
    <tr>
        <td>
        <?= $element['product']->title ?>
        </td>
        <td><?= $element['quantity'] ?></td>
        <td><?= $element['product']->price ?>€</td>
        <td><?= $element['quantity'] * $element['product']->price ?> €</td>
    </tr>
    <?php endforeach ?>
</tbody>

</table>

</main>
<?php   $_SESSION=session_destroy();
  ?>