<div class="container">
<!-- <?php if (!isset($_SESSION['panier'])) {
    $_SESSION['panier'] = [];
};
$panier = $_SESSION['panier'];
// var_dump($_POST);
?> -->
        <h2 class="text_bio"><span>Les produits<span></h2>
      
        <table class="commande">
           
            <?php foreach ($products as $product) : ?>
                <tr>
                    <td>
                        <h3> <?= $product->title ?> (<?= $product->price ?> €) </h3>
                    </td>

                    <form action="index.php?controller=PanierTest&task=indexPanier" method="POST" class="formpanier">
                        <td>
                            <input type="hidden" name="id" value="<?= ucfirst(strtolower($product->id)) ?>" class="formpanier">
                            <input type="number" name="quantity" id="" placeholder="quantité"  min="0" size="3" class="formpanier">

                            <button type="submit" id="add" ><strong>+</strong></button>
                            <!-- <a href="javascript:" data-id="<?= $product->id?>" class="add"><i class="flaticon-bag" ><span>ADD TO CART</span></i></a> -->
                        </td>
                </tr>
               
                </form>
            <?php endforeach ?>
           
        </table>
    
<!-- <script>
document.getElementById('add').onclick = function(){
    return false;
}
</script> -->

<h1>Votre panier</h1>
<table>
<thead>
    <tr>
    <th>Plat</th>
    <th>Quantité</th>
    <th>Prix</th>
    <th>Prix Total</th>
    <th></th>
    </tr>
</thead>

<tbody>
    <?php foreach ($panier as $element) : ?>
    <tr>
        <td>
            <?= $element['product']->title ?>
        </td>
        <td>
            <form action="index.php?controller=PanierTest&task=updateItem" method="post" >
                <input type="hidden" name="id" value="<?= $element['product']->id ?>">
                <input type="number" name="quantity" id="" placeholder="quantity" min=1 required="required" value="<?= $element['quantity'] ?>" onchange="this.form.submit()">
                <button type="submit">Envoi</button>
            </form>    
        </td>
        <td><?= $element['product']->price ?>€</td>
        <td><?= $element['quantity'] * $element['product']->price ?> €</td>
        <td>
            <a href="index.php?controller=PanierTest&task=deleteItem&id=<?= $element['product']->id ?>" class="mod">supprimer</a>
        </td>
    </tr>
    <?php endforeach ?>
</tbody>


</table>
<!-- // SELECT plats.id, plats.photo, plats.nom_plat, plats.prix, orders_plat.quantity, (plats.prix* orders_plat.quantity) as total
FROM plats
JOIN orders_plat ON orders_plat.plat_id=plats.id
WHERE orders_plat.order_id=1 -->
<a href="index.php?controller=PanierTest&task=indexPanier" class="mod">Rajouter des plats</a>
<a href="../index.php?controller=Panier&task=addOrder" class="mod">commander</a>
<script>
document.querySelector('mod').onclick = function(){
    return false;
}
</script>

</main>
